---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: iac-challenge-app
  name: iac-challenge-app
spec:
  replicas: 3
  selector:
    matchLabels:
      run: iac-challenge-app
  template:
    metadata:
      labels:
        run: iac-challenge-app
    spec:
      containers:
      - name: iac-app
        image: DOCKER_TAG
        ports:
        - containerPort: 3000
          protocol: TCP
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: iac-challenge-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iac-app
  template:
    metadata:
      labels:
        app: iac-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app-node
                operator: In
                values:
                - "1"
                - "2"
                - "3"
      containers:
      - name: iac-app
        image: DOCKER_TAG
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: iac-app-service
spec:
  selector:
    app: iac-app
  ports:
    - protocol: TCP
      port: 3000  # Puerto externo del servicio
      targetPort: 3000  # Puerto interno del contenedor
  type: LoadBalancer  # Tipo de servicio LoadBalancer para exponer externamente en GKE

