name: Connect and Deploy to GKE

on:
  push:
    branches:
      - develop

#env:
#  PROJECT_ID: iacchalenge
#  GKE_CLUSTER: iac-gke-cluster   
#  GKE_ZONE: us-central1   
#  DEPLOYMENT_NAME: iac-app 
jobs:
  setup-build-publish-deploy:
    name: Setup, Connect, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: 'iac-gke-cluster'
        location: 'us-central1'
    - id: 'get-pods'
      run: 'kubectl get pods'