name: Build and Deploy to GKE

on:
  push:
    branches:
      - develop

env:
  PROJECT_ID: iacchalenge
  GKE_CLUSTER: iac-gke-cluster    # Add your cluster name here.
  GKE_ZONE: us-central1   # Add your cluster zone here.
  DEPLOYMENT_NAME: iac-app # Add your deployment name here.
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ env.GKE_PROJECT }}

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        kubectl get services -o wide
        kubectl get nodes -o wide