name: Connect and Deploy to GKE

on:
  workflow_run:
    workflows: ["golang-pipeline-deploy-GKE"]
    types:
      - completed
jobs:
  setup-build-publish-deploy:
    name: Setup, Connect, and Deploy
    runs-on: ubuntu-latest
    needs: golang-pipeline-deploy-GKE
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Extract Version
      id: version_step
      run: |
        echo "##[set-output name=latest_tag;]$GITHUB_REPOSITORY:latest"
        echo "##[set-output name=version_tag;]$GITHUB_REPOSITORY:${GITHUB_REF#$"refs/tags/v"}"      
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: 'iac-gke-cluster'
        location: 'us-central1'
    - id: 'get-pods'
      run: |
        kubectl get pods
        cat ../iac-app-deployment.yml | sed "s/{{DOCKER_TAG}}/${{ env.VERSION_TAG }}" | kubectl apply -f -
        kubectl get nodes